apiVersion: v1
kind: Secret
metadata:
  name: anamnesis-secrets
  namespace: default
type: Opaque
stringData:
  database-url: "postgres://anamnesis_app:root@anamnesis-rw:5432/anamnesis?sslmode=disable"
  jwt-secret: "root"


