apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - app/migrate-job.yaml
  - app/deployment.yaml
  - app/service.yaml
  - app/hpa.yaml
  - app/ingress.yaml
  - web/deployment.yaml
  - postgres/cnpg-cluster.yaml
  - postgres/pdb.yaml
  - postgres/scheduled-backup.yaml
  - secrets/minio-secrets.yaml
  - secrets/cnpg-superuser.yaml
  - secrets/anamnesis-app-owner.yaml
  - secrets/cnpg-s3.yaml
  - secrets/anamnesis-db-secrets.yaml
  - secrets/anamnesis-secrets.yaml
  - backup/backup-pvc.yaml
  - backup/minio.yaml
  - app/pdb.yaml
  - web/pdb.yaml
  - events/nats.yaml
  - security/network-policies.yaml
  - security/service-accounts.yaml
  - observability/prometheus.yaml
  - observability/prometheus-config.yaml
  - observability/alertmanager.yaml
  - observability/loki.yaml
  - observability/promtail.yaml
  - observability/postgres-exporter.yaml
  - observability/postgres-exporter-queries.yaml
  - observability/blackbox-exporter.yaml
  - observability/grafana.yaml
  - observability/kube-state-metrics.yaml
  - observability/node-exporter.yaml
  - observability/ingress.yaml
  - observability/tempo.yaml
  - security/allow-cnpg-api.yaml
  - security/allow-migrate.yaml
  - security/allow-postgres-exporter.yaml
  - security/allow-prometheus.yaml
  - security/allow-grafana.yaml
  - security/allow-grafana-pg.yaml
  - security/allow-grafana-egress-pg.yaml
  - security/allow-grafana-ingress.yaml
  - security/allow-loki.yaml
  - security/allow-tempo.yaml
  - security/allow-nats.yaml
  - security/allow-app-egress.yaml
  - security/allow-promtail-api.yaml
  - security/allow-scrape-ingress.yaml
  - security/pki.yaml
  - observability/grafana-dashboard-provider.yaml
  - observability/grafana-dashboards.yaml
  - observability/grafana-node-dashboard.yaml
  - observability/grafana-ingress.yaml
  - observability/blackbox-probe.yaml
