apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tempo
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: tempo
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: grafana
      ports:
        - protocol: TCP
          port: 3200
    - from:
        - podSelector:
            matchLabels:
              app: anamnesis-api
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
