apiVersion: v1
kind: ServiceAccount
metadata:
  name: anamnesis-api
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anamnesis-backup
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-exporter
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: ["nodes","nodes/metrics","services","endpoints","pods"]
    verbs: ["get","list","watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: default
