apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anamnesis-api
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: anamnesis-ca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - anamnesis.local
      secretName: anamnesis-tls
  rules:
    - host: anamnesis.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: anamnesis-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anamnesis-web
                port:
                  name: http
