apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: anamnesis-nightly
  namespace: default
spec:
  schedule: "0 0 1 * * *"
  backupOwnerReference: cluster
  cluster:
    name: anamnesis