apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: anamnesis-preview
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - pullRequest:
        repo: https://github.com/YOUR_GH_USER/anamnesis.git
        requeueAfterSeconds: 180
        github:
          tokenRef:
            secretName: github-token
            key: token
  template:
    metadata:
      name: pr-{{branch_slug}}
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_GH_USER/anamnesis.git
        path: k8s/overlays/preview
        targetRevision: "{{ head_sha }}"
        kustomize:
          images:
            - ghcr.io/YOUR_GH_USER/anamnesis:pr-{{number}}
          patches:
            - target:
                group: networking.k8s.io
                kind: Ingress
                name: anamnesis-api
              patch: |
                - op: replace
                  path: /spec/rules/0/host
                  value: "pr-{{-number}}.anamnesis.local"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true