apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox
  namespace: default
spec:
  endpoints:
    - port: probe
      params:
        module:
          - http_2xx
        target:
          - https://anamnesis.example.com
  targetLabels:
    - job
    - k8s_cluster