apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
      - name: Postgres Exporter
        type: prometheus
        access: proxy
        url: http://prometheus:9090
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
      - name: AnamnesisDB
        type: postgres
        access: proxy
        url: anamnesis-ro:5432
        user: anamnesis_readonly
        secureJsonData:
          password: "readonly"
        jsonData:
          database: anamnesis
          sslmode: disable
          postgresVersion: 1700
kind: ConfigMap
metadata:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"datasources.yaml":"apiVersion: 1\ndatasources:\n  - name: Prometheus\n    type: prometheus\n    access: proxy\n    url: http://prometheus:9090\n    isDefault: true\n  - name: Loki\n    type: loki\n    access: proxy\n    url: http://loki:3100\n  - name: Postgres Exporter\n    type: prometheus\n    access: proxy\n    url: http://prometheus:9090\n  - name: Tempo\n    type: tempo\n    access: proxy\n    url: http://tempo:3200\n  - name: AnamnesisDB\n    uid: anamnesisdb\n    type: postgres\n    access: proxy\n    url: anamnesis-ro:5432\n    user: anamnesis_readonly\n    secureJsonData:\n      password: \"readonly\"\n    jsonData:\n      database: anamnesis\n      sslmode: disable\n      postgresVersion: 1700\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"grafana-datasources","namespace":"default"}}
  name: grafana-datasources
  namespace: default
