apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: anamnesis
        metrics_path: /api/v1/metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: "${1}:8080"

      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: node-exporter
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: "${1}:9100"

      - job_name: kube-state-metrics
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: kube-state-metrics
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: "${1}:8080"

      - job_name: postgres
        static_configs:
          - targets: ["postgres-exporter:9187"]
            labels:
              component: database

      - job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets: ["http://anamnesis-api:80/api/v1/_health"]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
kind: ConfigMap
metadata:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\nscrape_configs:\n  - job_name: prometheus\n    static_configs:\n      - targets: [\"localhost:9090\"]\n\n  - job_name: anamnesis\n    metrics_path: /api/v1/metrics\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n        regex: \"true\"\n        action: keep\n      - source_labels: [__meta_kubernetes_pod_ip]\n        target_label: __address__\n        replacement: \"${1}:8080\"\n\n  - job_name: node-exporter\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_pod_label_app]\n        regex: node-exporter\n        action: keep\n      - source_labels: [__meta_kubernetes_pod_ip]\n        target_label: __address__\n        replacement: \"${1}:9100\"\n\n  - job_name: kube-state-metrics\n    kubernetes_sd_configs:\n      - role: pod\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_pod_label_app]\n        regex: kube-state-metrics\n        action: keep\n      - source_labels: [__meta_kubernetes_pod_ip]\n        target_label: __address__\n        replacement: \"${1}:8080\"\n\n  - job_name: postgres\n    static_configs:\n      - targets: [\"postgres-exporter:9187\"]\n        labels:\n          component: database\n\n  - job_name: blackbox\n    metrics_path: /probe\n    params:\n      module: [http_2xx]\n    static_configs:\n      - targets: [\"http://anamnesis-api:80/api/v1/_health\"]\n    relabel_configs:\n      - source_labels: [__address__]\n        target_label: __param_target\n      - source_labels: [__param_target]\n        target_label: instance\n      - target_label: __address__\n        replacement: blackbox-exporter:9115\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config","namespace":"default"}}
  name: prometheus-config
  namespace: default
